apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: inquiry-guestbook
  labels:
    cloud.googleapis.com/location: asia-northeast1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/network-interfaces: '[{"network":"qwiklabs-handson-network","subnetwork":"asia-northeast1","tags":["run-direct-egress"]}]'
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: 80
      timeoutSeconds: 30
      containers:
        - image: asia-northeast1-docker.pkg.dev/PROJECT_ID/qwiklabs-apps/inquiry-guestbook:v1.0
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: 'IP_ADDRESS'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
